In [2]:
from sklearn.linear_model import LinearRegression, Lasso
import numpy as np
import pandas as pd

In [3]:
x1 = np.array([1,4,6,4])
x2 = np.array([2,1,2,3])
x3 = np.array([3,2,6,2])
y = np.array([8,11,18,17])

In [4]:
X = np.stack([x1,x2,x3], axis=1)
X

array([[1, 2, 3],
       [4, 1, 2],
       [6, 2, 6],
       [4, 3, 2]])

In [5]:
reg = LinearRegression().fit(X, y)

In [6]:
reg.coef_

array([ 2.00000000e+00,  3.00000000e+00, -1.22124533e-15])

In [7]:
lasso = Lasso(alpha=1).fit(X,y)

In [8]:
lasso.coef_

array([1.68627451, 1.        , 0.        ])

In [9]:
lasso = Lasso(alpha=0.1).fit(X,y)

In [10]:
lasso.coef_

array([1.96862745, 2.8       , 0.        ])

In [11]:
lasso = Lasso(alpha=0.01).fit(X,y)
lasso.coef_

array([1.99686275, 2.98      , 0.        ])

In [74]:
lasso = Lasso(alpha=0.01).fit(X,y)
lasso.coef_

NameError: name 'y' is not defined

In [131]:
data = pd.read_csv('Cleaned 2013_2014.csv')
data

6-digit OPE ID for institution  \
0                               1002   
1                               1004   
2                               1005   
3                               1009   
4                               1012   
5                               1016   
6                               1019   
7                               1020   
8                               1023   
9                               1024   
10                              1029   
11                              1033   
12                              1036   
13                              1041   
14                              1044   
15                              1047   
16                              1050   
17                              1051   
18                              1052   
19                              1055   
20                              1057   
21                              1061   
22                              1081   
23                              1082   
24                              1083   
25                              1086   
26                              1088   
27                              1089   
28                              1090   
29                              1092   
...                              ...   
1238                           12580   
1239                           20530   
1240                           20653   
1241                           20662   
1242                           20705   
1243                           20758   
1244                           21064   
1245                           21078   
1246                           21366   
1247                           21415   
1248                           21567   
1249                           21596   
1250                           21691   
1251                           22345   
1252                           22704   
1253                           22706   
1254                           23172   
1255                           23580   
1256                           25762   
1257                           30113   
1258                           30719   
1259                           30888   
1260                           30913   
1261                           31019   
1262                           31155   
1263                           32553   
1264                           32603   
1265                           34403   
1266                           37243   
1267                           39803   

      Admission rate for all campuses rolled up to the 6-digit OPE ID  \
0                                              0.898900                 
1                                              0.872900                 
2                                              0.512500                 
3                                              0.827400                 
4                                              0.642200                 
5                                              0.809200                 
6                                              0.627900                 
7                                              0.832600                 
8                                              0.738800                 
9                                              0.995700                 
10                                             0.712500                 
11                                             0.343500                 
12                                             0.769700                 
13                                             0.462700                 
14                                             0.430000                 
15                                             0.682100                 
16                                             0.351100                 
17                                             0.565500                 
18                                             0.867300                 
19                                             0.806200          

In [132]:
Y = data['Nat Log Mean earnings of students working and not enrolled 10 years after entry']
Y.head()
# Median earnings of students working and not enrolled 10 years after entry

0    10.442901
1    10.491274
2    10.292146
3    10.898589
4    10.839581
Name: Nat Log Mean earnings of students working and not enrolled 10 years after entry, dtype: float64

In [133]:
X = data.drop(columns=['Nat Log Mean earnings of students working and not enrolled 10 years after entry','Unnamed: 14','Unnamed: 15'])
X.head()

6-digit OPE ID for institution  \
0                            1002   
1                            1004   
2                            1005   
3                            1009   
4                            1012   

   Admission rate for all campuses rolled up to the 6-digit OPE ID  \
0                                             0.8989                 
1                                             0.8729                 
2                                             0.5125                 
3                                             0.8274                 
4                                             0.6422                 

   Average SAT equivalent score of students admitted for all campuses rolled up to the 6-digit OPE ID  \
0                                                823                                                    
1                                               1070                                                    
2                                                830                                                    
3                                               1215                                                    
4                                               1177                                                    

   Proportion of faculty that is full-time  \
0                                   0.8856   
1                                   0.5951   
2                                   0.6641   
3                                   0.8780   
4                                   0.6479   

   First-time, full-time student retention rate at four-year institutions  \
0                                             0.6314                        
1                                             0.7365                        
2                                             0.6219                        
3                                             0.8946                        
4                                             0.8037                        

   The median debt for students who have completed  Average age of entry  \
0                                          29500.0             20.540410   
1                                          22500.0             21.791473   
2                                          31200.0             20.648575   
3                                          21500.0             20.600619   
4                                          27000.0             19.693512   

   Average family income in real 2015 dollars  \
0                                 29598.38641   
1                                 53709.14341   
2                                 28112.46513   
3                                 90266.79915   
4                                 92290.00447   

   Mean earnings of students working and not enrolled 6 years after entry  \
0                                              27200                        
1                                              27000                        
2                                              23100                        
3                                              40300                        
4                                              35700                        

   Mean earnings of students working and not enrolled 8 years after entry  \
0                                              29700                        
1                                              31600                        
2                                              26000                        
3                                              48500                        
4                                              41100                        

   Mean earnings of students working and not enrolled 10 years after entry  \
0                                              34300                         
1                                              36000                         
2                                              29500                        

In [134]:
lasso = Lasso(alpha=1).fit(X,Y)
lasso

Lasso(alpha=1, copy_X=True, fit_intercept=True, max_iter=1000, normalize=False,
      positive=False, precompute=False, random_state=None, selection='cyclic',
      tol=0.0001, warm_start=False)

In [135]:
lasso.coef_

array([-2.18480792e-07,  0.00000000e+00, -0.00000000e+00, -0.00000000e+00,
        0.00000000e+00, -7.40185674e-07,  0.00000000e+00,  1.24111287e-06,
        2.09022856e-06, -2.23834450e-06,  1.68363762e-05, -4.88396153e-07,
        0.00000000e+00])

In [136]:
X.columns

Index(['6-digit OPE ID for institution',
       'Admission rate for all campuses rolled up to the 6-digit OPE ID',
       'Average SAT equivalent score of students admitted for all campuses rolled up to the 6-digit OPE ID',
       'Proportion of faculty that is full-time',
       'First-time, full-time student retention rate at four-year institutions',
       'The median debt for students who have completed',
       'Average age of entry', 'Average family income in real 2015 dollars',
       'Mean earnings of students working and not enrolled 6 years after entry',
       'Mean earnings of students working and not enrolled 8 years after entry',
       'Mean earnings of students working and not enrolled 10 years after entry',
       'Average cost of attendance (academic year institutions)',
       'Completion rate for first-time, full-time students at four-year institutions (150% of expected time to completion)'],
      dtype='object')

In [137]:
lasso_results = pd.DataFrame()

In [138]:
lasso_results['feature']=X.columns

In [139]:
lasso_results['coef']=lasso.coef_

In [140]:
lasso_results

feature          coef
0                      6-digit OPE ID for institution -2.184808e-07
1   Admission rate for all campuses rolled up to t...  0.000000e+00
2   Average SAT equivalent score of students admit... -0.000000e+00
3             Proportion of faculty that is full-time -0.000000e+00
4   First-time, full-time student retention rate a...  0.000000e+00
5     The median debt for students who have completed -7.401857e-07
6                                Average age of entry  0.000000e+00
7          Average family income in real 2015 dollars  1.241113e-06
8   Mean earnings of students working and not enro...  2.090229e-06
9   Mean earnings of students working and not enro... -2.238344e-06
10  Mean earnings of students working and not enro...  1.683638e-05
11  Average cost of attendance (academic year inst... -4.883962e-07
12  Completion rate for first-time, full-time stud...  0.000000e+00

In [120]:
reg = LinearRegression().fit(X, Y)

In [121]:
reg.coef_

array([-6.14213751e-07,  6.04994880e-02, -3.07174152e-05, -2.29997470e-02,
        1.51313347e-01, -5.99142015e-07,  4.61220578e-03,  1.29166505e-06,
        6.49918904e-07, -2.42504634e-06,  1.79977542e-05, -4.89571091e-07,
       -1.16269117e-02])

In [122]:
linear_results = pd.DataFrame()
linear_results['feature']=X.columns
linear_results['coef']=reg.coef_

In [123]:
linear_results

feature          coef
0                      6-digit OPE ID for institution -6.142138e-07
1   Admission rate for all campuses rolled up to t...  6.049949e-02
2   Average SAT equivalent score of students admit... -3.071742e-05
3             Proportion of faculty that is full-time -2.299975e-02
4   First-time, full-time student retention rate a...  1.513133e-01
5     The median debt for students who have completed -5.991420e-07
6                                Average age of entry  4.612206e-03
7          Average family income in real 2015 dollars  1.291665e-06
8   Mean earnings of students working and not enro...  6.499189e-07
9   Mean earnings of students working and not enro... -2.425046e-06
10  Mean earnings of students working and not enro...  1.799775e-05
11  Average cost of attendance (academic year inst... -4.895711e-07
12  Completion rate for first-time, full-time stud... -1.162691e-02

In [124]:
C = data['Nat Log Mean earnings of students working and not enrolled 10 years after entry'].mean()
C

10.767365489700317

In [125]:
m = data['Nat Log Mean earnings of students working and not enrolled 10 years after entry'].quantile(0.90)
print(m)

11.073334387000001


In [128]:
q = data.copy().loc[data['Nat Log Mean earnings of students working and not enrolled 10 years after entry'] >= m]

In [130]:
q.shape

(127, 16)