In [2]:
from sklearn.linear_model import LinearRegression, Lasso
import numpy as np
import pandas as pd

In [3]:
x1 = np.array([1,4,6,4])
x2 = np.array([2,1,2,3])
x3 = np.array([3,2,6,2])
y = np.array([8,11,18,17])

In [4]:
X = np.stack([x1,x2,x3], axis=1)
X

array([[1, 2, 3],
       [4, 1, 2],
       [6, 2, 6],
       [4, 3, 2]])

In [5]:
reg = LinearRegression().fit(X, y)

In [6]:
reg.coef_

array([ 2.00000000e+00,  3.00000000e+00, -1.22124533e-15])

In [7]:
lasso = Lasso(alpha=1).fit(X,y)

In [8]:
lasso.coef_

array([1.68627451, 1.        , 0.        ])

In [9]:
lasso = Lasso(alpha=0.1).fit(X,y)

In [10]:
lasso.coef_

array([1.96862745, 2.8       , 0.        ])

In [11]:
lasso = Lasso(alpha=0.01).fit(X,y)
lasso.coef_

array([1.99686275, 2.98      , 0.        ])

In [12]:
lasso = Lasso(alpha=0.001).fit(X,y)
lasso.coef_

array([1.99968627, 2.998     , 0.        ])

In [21]:
data = pd.read_csv('MERGED2014_15_PP.csv')
data

UNITID     OPEID  OPEID6  \
0       100654    100200    1002   
1       100663    105200    1052   
2       100690   2503400   25034   
3       100706    105500    1055   
4       100724    100500    1005   
5       100751    105100    1051   
6       100760    100700    1007   
7       100812    100800    1008   
8       100830    831000    8310   
9       100858    100900    1009   
10      100937    101200    1012   
11      101028   1218200   12182   
12      101073   1055400   10554   
13      101116   1303906   13039   
14      101143    101500    1015   
15      101161    106000    1060   
16      101189    100300    1003   
17      101240    101700    1017   
18      101277   4187200   41872   
19      101286    101800    1018   
20      101295    787100    7871   
21      101301    569900    5699   
22      101365    962107    9621   
23      101435    101900    1019   
24      101453   2199700   21997   
25      101462    526000    5260   
26      101480    102000    1020   
27      101499    102100    1021   
28      101505    102200    1022   
29      101514    101300    1013   
...        ...       ...     ...   
7673  45775802   4149302   41493   
7674  45776701   4154901   41549   
7675  45891901    145940    1459   
7676  45891902    145946    1459   
7677  45891903    145952    1459   
7678  45891904    145959    1459   
7679  45891905    145965    1459   
7680  45891906    145971    1459   
7681  45891907    145972    1459   
7682  45891908    145996    1459   
7683  45896401    145945    1459   
7684  45896402    145954    1459   
7685  45897301    145990    1459   
7686  45897302    145992    1459   
7687  45897303    145994    1459   
7688  45897304    145995    1459   
7689  45897305  10145900    1459   
7690  45897306  10145901    1459   
7691  45897307  10145908    1459   
7692  45897308  10145909    1459   
7693  45920401   4169701   41697   
7694  47647001   4088301   40883   
7695  47657701   4184801   41848   
7696  47657702   4184802   41848   
7697  47691101   4205801   42058   
7698  48065701    869423    8694   
7699  48154401   4220901   42209   
7700  48387801   4223701   42237   
7701  48400201   4228101   42281   
7702  48414501   4232401   42324   

                                                 INSTNM              CITY  \
0                              Alabama A & M University            Normal   
1                   University of Alabama at Birmingham        Birmingham   
2                                    Amridge University        Montgomery   
3                   University of Alabama in Huntsville        Huntsville   
4                              Alabama State University        Montgomery   
5                             The University of Alabama        Tuscaloosa   
6                     Central Alabama Community College    Alexander City   
7                               Athens State University            Athens   
8                       Auburn University at Montgomery        Montgomery   
9                                     Auburn University            Auburn   
10                          Birmingham Southern College        Birmingham   
11               Chattahoochee Valley Community College       Phenix City   
12                            Concordia College Alabama             Selma   
13                          South University-Montgomery        Montgomery   
14                   Enterprise State Community College        Enterprise   
15                    Coastal Alabama Community College       Bay Minette   
16                                  Faulkner University        Montgomery   
17                      Gadsden State Community College           Gadsden   
18                 New Beginning College of Cosmetology       Albertville   
19            George C Wallace Community College-Dothan            Dothan   
20    George C Wallace State Community College-Hance...        Hanceville   
21       George C Wallace State Community College-Selma             Selma   
22  

In [24]:
Y = data['MD_EARN_WNE_P10']
# Median earnings of students working and not enrolled 10 years after entry

In [35]:
X = data.select_dtypes(include=['float64', 'int'])
X.head()

UNITID    OPEID  OPEID6  ACCREDAGENCY  INSTURL  NPCURL  SCH_DEG  HCM2  \
0  100654   100200    1002           NaN      NaN     NaN      3.0   NaN   
1  100663   105200    1052           NaN      NaN     NaN      3.0   NaN   
2  100690  2503400   25034           NaN      NaN     NaN      3.0   NaN   
3  100706   105500    1055           NaN      NaN     NaN      3.0   NaN   
4  100724   100500    1005           NaN      NaN     NaN      3.0   NaN   

   MAIN  NUMBRANCH  ...  OMAWDP8_NOTFIRSTTIME_POOLED_SUPP  \
0     1          1  ...                               NaN   
1     1          1  ...                               NaN   
2     1          1  ...                               NaN   
3     1          1  ...                               NaN   
4     1          1  ...                               NaN   

   OMENRUP_NOTFIRSTTIME_POOLED_SUPP  OMENRYP_FULLTIME_POOLED_SUPP  \
0                               NaN                           NaN   
1                               NaN                           NaN   
2                               NaN                           NaN   
3                               NaN                           NaN   
4                               NaN                           NaN   

   OMENRAP_FULLTIME_POOLED_SUPP  OMAWDP8_FULLTIME_POOLED_SUPP  \
0                           NaN                           NaN   
1                           NaN                           NaN   
2                           NaN                           NaN   
3                           NaN                           NaN   
4                           NaN                           NaN   

   OMENRUP_FULLTIME_POOLED_SUPP  OMENRYP_PARTTIME_POOLED_SUPP  \
0                           NaN                           NaN   
1                           NaN                           NaN   
2                           NaN                           NaN   
3                           NaN                           NaN   
4                           NaN                           NaN   

   OMENRAP_PARTTIME_POOLED_SUPP  OMAWDP8_PARTTIME_POOLED_SUPP  \
0                           NaN                           NaN   
1                           NaN                           NaN   
2                           NaN                           NaN   
3                           NaN                           NaN   
4                           NaN                           NaN   

   OMENRUP_PARTTIME_POOLED_SUPP  
0                           NaN  
1                           NaN  
2                           NaN  
3                           NaN  
4                           NaN  

[5 rows x 726 columns]

In [38]:
lasso = Lasso(alpha=1).fit(X,Y)
lasso

ValueError: Input contains NaN, infinity or a value too large for dtype('float64').